name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    # Run build and tests for each Swift version and OS combination
    name: Build and Test on ${{ matrix.swift }} / ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os:
          - macos-13     # x86_64 (Intel)
          - macos-latest # arm64 (Apple Silicon)
        swift:
          - 5.10         # Xcode 15.3
          - 6.0          # Xcode 16

    steps:
      - uses: actions/checkout@v4

      - name: Select Xcode version for Swift ${{ matrix.swift }}
        run: |
          case "${{ matrix.swift }}" in
            5.10) sudo xcode-select -s /Applications/Xcode_15.3.app ;;
            6.0) sudo xcode-select -s /Applications/Xcode_16.0.app ;;
          esac

          # Print selected Xcode version for confirmation
          xcodebuild -version

      - name: Build
        run: swift build -v

      - name: Run tests
        run: swift test -v
